// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickMartPOSWeb.Models;

#nullable disable

namespace QuickMartPOSWeb.Migrations
{
    [DbContext(typeof(QuickMartContext))]
    [Migration("20250709185153_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("QuickMartPOSWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Grocery",
                            Name = "Rice (1 kg)",
                            Price = 1.20m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Grocery",
                            Name = "Flour (1 kg)",
                            Price = 0.90m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Grocery",
                            Name = "Sugar (1 kg)",
                            Price = 1.10m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Grocery",
                            Name = "Cooking Oil (1L)",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Grocery",
                            Name = "Salt (1 kg)",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Grocery",
                            Name = "Lentils (1 kg)",
                            Price = 1.80m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Grocery",
                            Name = "Turmeric (100g)",
                            Price = 0.60m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Grocery",
                            Name = "Tea (100g)",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Snacks",
                            Name = "Biscuits (pack)",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Snacks",
                            Name = "Potato Chips (pack)",
                            Price = 1.20m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Snacks",
                            Name = "Instant Noodles",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Snacks",
                            Name = "Chocolate Bar",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Beverages",
                            Name = "Soft Drink (500ml)",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Beverages",
                            Name = "Juice (1L)",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Beverages",
                            Name = "Beer",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Beverages",
                            Name = "Vodka",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Beverages",
                            Name = "Wine",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Dairy",
                            Name = "Milk (1L)",
                            Price = 1.20m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Dairy",
                            Name = "Butter (200g)",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Dairy",
                            Name = "Cheese (200g)",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Dairy",
                            Name = "Yogurt (200g)",
                            Price = 0.80m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Dairy",
                            Name = "Bread (loaf)",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Household",
                            Name = "Soap (bar)",
                            Price = 0.80m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Household",
                            Name = "Detergent (500g)",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Household",
                            Name = "Toothpaste (100g)",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Household",
                            Name = "Shampoo (200ml)",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 27,
                            Category = "Household",
                            Name = "Toilet Paper (roll)",
                            Price = 0.70m
                        },
                        new
                        {
                            Id = 28,
                            Category = "Personal Care",
                            Name = "Toothbrush",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 29,
                            Category = "Personal Care",
                            Name = "Hair Oil (100ml)",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 30,
                            Category = "Personal Care",
                            Name = "Deodorant",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 31,
                            Category = "Stationery",
                            Name = "Notebook",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 32,
                            Category = "Stationery",
                            Name = "Pen",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 33,
                            Category = "Stationery",
                            Name = "Batteries (AA, pack of 2)",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 34,
                            Category = "Stationery",
                            Name = "Lighter",
                            Price = 0.80m
                        });
                });

            modelBuilder.Entity("QuickMartPOSWeb.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("QuickMartPOSWeb.Models.TransactionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("QuickMartPOSWeb.Models.TransactionItem", b =>
                {
                    b.HasOne("QuickMartPOSWeb.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuickMartPOSWeb.Models.Transaction", null)
                        .WithMany("Items")
                        .HasForeignKey("TransactionId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QuickMartPOSWeb.Models.Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
